import test from 'node:test'
import assert from 'node:assert/strict'
import { Sequence, LayerState, rowOffsets, mix15, expand5, frameAt } from '../src/renderer/state.js'
import { ShuffleBag, eligibleScenes, normalizeSettings } from '../src/selection.js'

// Expected values below are hand-computed from the integer routines documented
// in docs/renderer.md. These are not screenshots generated by the renderer.
test('sequence starts at slot 1, loops through slot 0, and holds duration zero', () => {
  const sequence = new Sequence([1,2,3,0], [null,{duration:0},{duration:2},{duration:1}])
  assert.equal(sequence.step(),true); assert.equal(sequence.index,1)
  assert.equal(sequence.step(),false)
  assert.equal(sequence.step(),true); assert.equal(sequence.index,2)
  assert.equal(sequence.step(),true); assert.equal(sequence.index,0)
  for(let i=0;i<20;i++) assert.equal(sequence.step(),false)
})
test('zero first and second slots disable an effect, not raw layer zero', () => {
  const s = new Sequence([0,0,1,2], [null,{duration:1},{duration:1}])
  assert.equal(s.step(),false); assert.equal(s.current,null)
  assert.equal(s.step(),false)
})
test('scroll acceleration is applied before position; 16-bit negative wrap', () => {
  const c = Array(17).fill(0); c[9]=1
  const s = new LayerState(c,[null,{duration:0,vx:0xff00,vy:0,ax:1,ay:0}],[])
  s.step(); assert.equal(s.x,0xff01); assert.equal(s.x>>>8,255)
  s.step(); assert.equal(s.x,0xfe03); assert.equal(s.vx,0xff02)
})
test('effect transitions reload parameters and wrap phase/frequency', () => {
  const c = Array(17).fill(0); c[13]=1
  const s = new LayerState(c,[],[null,{duration:0,type:1,frequency:65535,amplitude:65535,phase:255,compression:65535,df:1,da:2,dp:2,dc:1}])
  s.step()
  assert.deepEqual([s.effect.frequency,s.effect.amplitude,s.effect.phase,s.effect.compression],[0,1,1,0])
})
test('palette speed uses simulation frames, including first identity update', () => {
  const c = Array(17).fill(0); c[3]=1; c[4]=1;c[5]=3;c[8]=2
  const s = new LayerState(c,[],[])
  s.step(); assert.equal(s.paletteIndex(1),1)
  s.step(); assert.equal(s.paletteIndex(1),1)
  s.step(); assert.equal(s.paletteIndex(1),3)
  s.step(); s.step(); assert.equal(s.paletteIndex(1),2)
  assert.equal(s.paletteIndex(0),0)
})
test('reverse palette cycle reflects at both ends', () => {
  const c = Array(17).fill(0); c[3]=3;c[4]=1;c[5]=3;c[8]=1
  const s = new LayerState(c,[],[])
  const values=[]; for(let i=0;i<7;i++){ s.step(); values.push(s.paletteIndex(1)) }
  assert.deepEqual(values,[1,2,3,3,2,1,1])
})
test('Mode 7 signed multiply floors negative products; alternating rows invert', () => {
  const s={x:0,y:0,effect:{type:2,phase:0,frequency:0,amplitude:256,compression:0}}
  const sine=Array(256).fill(255)
  assert.deepEqual(Array.from(rowOffsets(s,sine,new Int16Array(4))),[-1,1,-1,1])
})
test('vertical compression is incremented before each scanline', () => {
  const s={x:0,y:512,effect:{type:3,phase:0,frequency:0,amplitude:0,compression:256}}
  assert.deepEqual(Array.from(rowOffsets(s,Array(256).fill(0),new Int16Array(3))),[3,4,5])
})
test('5-bit color math averages before expansion with no channel carry', () => {
  assert.equal(mix15(31,0),15)
  assert.equal(mix15(31,31<<5),15 | 15<<5)
  assert.equal(expand5(31),255); assert.equal(expand5(0),0)
})
test('simulation time is independent of display refresh rate', () => {
  for(const hz of [30,60,120]) assert.equal(frameAt((hz*2)*1000/hz),120)
  assert.equal(frameAt(1000/60),1)
})
test('shuffle has no duplicates per bag or immediate repeat across bags', () => {
  const bag = new ShuffleBag(()=>0.5), items=['a','b','c','d']
  const a=items.map(()=>bag.next(items)), b=items.map(()=>bag.next(items))
  assert.equal(new Set(a).size,4); assert.equal(new Set(b).size,4); assert.notEqual(a.at(-1),b[0])
  assert.equal(bag.next([]),null)
})
test('favorites fallback never overrides explicit exclusions', () => {
  const scenes=[{id:'1:0'},{id:'2:0'}]
  const s=normalizeSettings({favoritesOnly:true,favorites:['1:0'],excluded:['1:0']})
  assert.deepEqual(eligibleScenes(scenes,s),[scenes[1]])
  assert.deepEqual(eligibleScenes(scenes,{...s,excluded:['1:0','2:0']}),[])
  assert.equal(normalizeSettings({interval:Infinity}).interval,300)
})

test('primary palette cycle overwrites overlapping secondary cycle',()=>{
  const c=Array(17).fill(0);c[3]=2;c[4]=1;c[5]=3;c[6]=0;c[7]=3;c[8]=1
  const s=new LayerState(c,[],[]);s.step();s.step()
  assert.equal(s.paletteIndex(1),3)
})
